project:
  type: website

# https://github.com/quarto-dev/quarto-cli/blob/main/src/resources/language/_language-fr.yml
lang: fr
language:
  fr:
    title-block-author-single: "Auteur"
    # title-block-author-plural: "Auteurs"
    # title-block-published: "Date de publication"
    appendix-attribution-cite-as: "Citation : "
    # appendix-attribution-bibtex: "Citation BibTeX : "
    # citation-appendix-title: "Suggestion de citation : "
    # section-title-footnotes: "Note de bas de page"

# NOTE : site-url and description for RSS feed 
website:
  title: "évologie"
  site-url: https://evologie.netlify.app
  description: "Réflexions sur l'évolution, la biodiversité et la vie"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/beausoleilmo
      - icon: linkedin
        href: https://www.linkedin.com/in/marcolivierbeausoleil/
      - icon: rss
        href: index.xml

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css

editor: visual

comments:
  giscus:
    repo: beausoleilmo/evologie
